### ISSUE TITLE
The demo on Huggingface is failed

### ISSUE THREAD

**Issue by ytl0623** [robmarkcole/fire-detection-from-images#41]
Hi, I was tried to test the demo on [Huggingface ](https://huggingface.co/spaces/robmarkcole/fire-detection-from-images), but got the error like below.
`Runtime error
l appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /home/user/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'custom', 'best.pt')  # force_reload=True to update
  File "/home/user/.local/lib/python3.8/site-packages/torch/hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/hub.py", line 587, in _load_local
    model = entry(*args, **kwargs)
  File "/home/user/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "/home/user/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "/home/user/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 28, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "/home/user/.cache/torch/hub/ultralytics_yolov5_master/utils/dataloaders.py", line 31, in <module>
    from utils.augmentations import (Albumentations, augment_hsv, classify_albumentations, classify_transforms, copy_paste,
  File "/home/user/.cache/torch/hub/ultralytics_yolov5_master/utils/augmentations.py", line 15, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box, xywhn2xyxy
  File "/home/user/.cache/torch/hub/ultralytics_yolov5_master/utils/general.py", line 38, in <module>
    from ultralytics.yolo.utils.checks import check_requirements
ModuleNotFoundError: No module named 'ultralytics'`

I think the problem may caused by the version of ultralytics.

Could you please solve this problem?

Thanks in advance!

**Comment by robmarkcole** [comment]
This is a tech debt so I am just removing
